### ISSUE TITLE
Error Barcode Generate

### ISSUE THREAD

**Issue by evedostomazi** [hjgode/barcodeLib#3]
Message:
EEAN13-3: Country assigning manufacturer code not found.
Code:
6996502953552

**Comment by hjgode** [comment]
69 or 699 is not a known country code. Anyway you shoiuld get a barcode, although the country code is unknown.

You may add 69 or 699 as your custom barcode country code inside https://github.com/hjgode/barcodeLib/blob/master/BarcodeLib/Symbologies/EAN13.cs.

**Comment by evedostomazi** [comment]
i received lot of tags with this code.

**Comment by hjgode** [comment]
That may be, you just have to change the file I mentioned. This is why the code is open source, you can change it yourself.
